# Generated by Django 2.2.24 on 2021-08-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.CharField(default='employee', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='generic', max_length=200),
        ),
    ]
