# Generated by Django 2.2.28 on 2023-04-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0002_auto_20230402_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='category',
        ),
    ]
