# Generated by Django 2.2.24 on 2021-08-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0003_auto_20210819_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='network',
        ),
    ]
