# Generated by Django 2.2.24 on 2022-05-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0004_remove_user_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cursus',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='office',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='campus',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard_api.Cursus'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard_api.Faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard_api.Job'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contact_email',
            field=models.EmailField(max_length=180),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contact_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='job_description',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='localization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='published_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='requirements',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='company_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
