# Generated by Django 2.2.24 on 2022-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0005_auto_20220526_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='contact_email',
            field=models.EmailField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contact_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='job_description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='localization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='requirements',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='url_redirection',
            field=models.URLField(max_length=740, null=True),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='company_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(null=True, upload_to='enterprise_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='username'),
        ),
    ]
