# Generated by Django 2.2.24 on 2022-05-26 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0006_auto_20220526_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='url_redirection',
            field=models.URLField(max_length=740, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='company_url',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
