# Generated by Django 2.2.24 on 2022-05-26 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0007_auto_20220526_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contact_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='job_description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='localization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='requirements',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='url_redirection',
            field=models.URLField(blank=True, max_length=740, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='company_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='enterprise_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cursus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard_api.Cursus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard_api.Faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard_api.Job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='ManagementCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cv_file/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
