# Generated by Django 2.2.28 on 2022-05-27 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0008_auto_20220526_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='logo',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
