# Generated by Django 2.2.28 on 2022-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard_api', '0009_auto_20220527_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
